---
- hosts: k8s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: containerd
    - role: download
    - role: kubeadm
    - role: storage

- hosts: master
  become: yes
  roles:
    - role: master
