- name: Update resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  register: resolved_conf

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  when: resolved_conf.changed
