---

- name: Install prerequisite packages
  apt:
    name:
      - containerd
    state: present

- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: Write containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    
